name: 'Yarn'

description: 'Install the dependencies'

runs:
  using: 'composite'
  steps:
    - name: Yarn cache
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
          /home/runner/.cache/Cypress
        key: web-core-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Yarn install
      shell: bash
      run: yarn install --frozen-lockfile
    - name: Yarn after install
      shell: bash
      run: yarn after-install
