name: Safe Apps e2e

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    name: Cypress Safe Apps tests
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/cypress
        with:
          secrets: ${{ toJSON(secrets) }}
          spec: cypress/e2e/safe-apps/*.cy.js
          group: 'Safe Apps tests'
          project_id: okn21k
          record_key: ${{ secrets.CYPRESS_SAFE_APPS_RECORD_KEY }}

