name: Tag & GitHub release

on:
  pull_request_target:
    branches:
      - main
    types: [closed]

jobs:
  tag-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version
        id: version
        run: |
          NEW_VERSION=$(node -p 'require("./package.json").version')
          echo "version=v$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create a git tag
        if: steps.version.outputs.version
        run: git tag ${{ steps.version.outputs.version }} && git push --tags

      - name: GitHub release
        if: steps.version.outputs.version
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          draft: true
          prerelease: false
          name: ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
          body: ${{ github.event.pull_request.body }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
