name: Unit tests
on:
  pull_request:

  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    permissions:
      contents: read
      checks: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/yarn

      - name: Annotations and coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.3.1
        with:
          skip-step: install
          annotations: failed-tests
          package-manager: yarn
          test-script: yarn test:ci
          github-token: ${{ secrets.GITHUB_TOKEN }}
